// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ilya-rusyanov/gophkeeper/internal/client/usecase/store (interfaces: AuthStorager)
//
// Generated by this command:
//
//	mockgen -destination ./mock/auth_storager.go -package mock . AuthStorager
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entity "github.com/ilya-rusyanov/gophkeeper/internal/client/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthStorager is a mock of AuthStorager interface.
type MockAuthStorager struct {
	ctrl     *gomock.Controller
	recorder *MockAuthStoragerMockRecorder
}

// MockAuthStoragerMockRecorder is the mock recorder for MockAuthStorager.
type MockAuthStoragerMockRecorder struct {
	mock *MockAuthStorager
}

// NewMockAuthStorager creates a new mock instance.
func NewMockAuthStorager(ctrl *gomock.Controller) *MockAuthStorager {
	mock := &MockAuthStorager{ctrl: ctrl}
	mock.recorder = &MockAuthStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthStorager) EXPECT() *MockAuthStoragerMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockAuthStorager) Load() (entity.MyAuthentication, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(entity.MyAuthentication)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockAuthStoragerMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockAuthStorager)(nil).Load))
}
