// Code generated by MockGen. DO NOT EDIT.
// Source: ./learn/go-advanced/gophkeeper/internal/client/usecase/store/store_test.go
//
// Generated by this command:
//
//	mockgen -source ./learn/go-advanced/gophkeeper/internal/client/usecase/store/store_test.go -package mocks -destination ./learn/go-advanced/gophkeeper/internal/client/usecase/store/mocks/mock_store_test.go
//

// Package mocks is a generated GoMock package.
package mocks
